# Generated by Django 3.2.7 on 2021-09-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_topics_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(default='', max_length=255, verbose_name='Источник'),
        ),
    ]
