# Generated by Django 3.2.7 on 2021-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_problem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
    ]
