# Generated by Django 3.2.7 on 2021-09-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_problem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование подтемы')),
                ('slug', models.SlugField(unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic', verbose_name='Тематика')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subtopic', verbose_name='Подтема'),
        ),
    ]
