# Generated by Django 3.2.7 on 2021-09-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210928_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='subtopic',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
