# Generated by Django 3.2.7 on 2021-11-06 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0013_auto_20211012_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_related_problems', to='mainapp.branch', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='PDBUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AlterField(
            model_name='featured',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pdbuser', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='featuredproblem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pdbuser', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
