# Generated by Django 3.2.7 on 2021-11-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20211106_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
