# Generated by Django 3.2.7 on 2021-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_pdbuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbuser',
            name='editor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Редактор'),
        ),
    ]
