# Generated by Django 3.2.7 on 2021-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_pdbuser_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждение email'),
        ),
    ]
