# Generated by Django 3.2.7 on 2021-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_pdbuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproblem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='topic',
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ManyToManyField(to='mainapp.Topic', verbose_name='Тема'),
        ),
    ]
