# Generated by Django 3.2.7 on 2021-11-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20211114_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_related_problems', to='mainapp.branch', verbose_name='Раздел'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='topic',
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic', verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
