# Generated by Django 3.2.7 on 2021-11-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20211116_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproblem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='featuredproblem',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='featuredproblem',
            name='student',
        ),
        migrations.RemoveField(
            model_name='pdbuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
        migrations.DeleteModel(
            name='FeaturedProblem',
        ),
        migrations.DeleteModel(
            name='PDBUser',
        ),
    ]
