# Generated by Django 3.2.7 on 2021-11-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mainapp', '0020_auto_20211116_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pdbuser', verbose_name='Владелец')),
                ('problems', models.ManyToManyField(blank=True, to='mainapp.Problem')),
            ],
        ),
    ]
