# Generated by Django 3.2.7 on 2021-11-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mainapp', '0023_auto_20211117_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_choices',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Варианты ответа'),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_type',
            field=models.CharField(choices=[('ED', 'Один ответ'), ('MP', 'Несколько ответов'), ('EX', 'Развернутый ответ')], default='EX', max_length=255, verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='featuredproblems',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_problems', to='users.pdbuser', verbose_name='Владелец'),
        ),
    ]
