# Generated by Django 3.2.7 on 2021-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20211120_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='extended_answer',
        ),
    ]
