# Generated by Django 3.2.7 on 2021-11-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_problem_extended_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
    ]
