# Generated by Django 3.2.7 on 2021-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_remove_problem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer_type',
            field=models.CharField(choices=[('ED', 'Один'), ('MP', 'Несколько'), ('NM', 'Число'), ('EX', 'Развернутый')], default='EX', max_length=255, verbose_name='Тип ответа'),
        ),
    ]
