# Generated by Django 3.2.7 on 2021-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_alter_problem_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Числовой ответ'),
        ),
    ]
