# Generated by Django 3.2.7 on 2021-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ipclient'),
        ('mainapp', '0029_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='views_count',
        ),
        migrations.AddField(
            model_name='problem',
            name='viewed_ips',
            field=models.ManyToManyField(blank=True, null=True, to='users.IPClient'),
        ),
        migrations.AlterField(
            model_name='featuredproblems',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_featured', to='mainapp.Problem'),
        ),
    ]
